// File generated by FlutterFire CLI.
// Este arquivo será gerado automaticamente quando você executar:
// flutter pub global activate flutterfire_cli
// flutterfire configure
//
// Por enquanto, este é um placeholder.
// Para configurar o Firebase:
// 1. Crie um projeto no Firebase Console (https://console.firebase.google.com)
// 2. Execute: flutter pub global activate flutterfire_cli
// 3. Execute: flutterfire configure
// 4. Este arquivo será substituído automaticamente

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx6IW9WmDSkbrYhVFu706X1YUdP4noQMM',
    appId: '1:804086085402:web:5c0deb1fcec9affc585ea3',
    messagingSenderId: '804086085402',
    projectId: 'monarch-ap',
    authDomain: 'monarch-ap.firebaseapp.com',
    storageBucket: 'monarch-ap.firebasestorage.app',
    measurementId: 'G-ENJGFSQVHP',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQvvinCH7Enx8W__Xj2zJyGTIK7XLWPAY',
    appId: '1:804086085402:ios:6f1b37ba16975cf0585ea3',
    messagingSenderId: '804086085402',
    projectId: 'monarch-ap',
    storageBucket: 'monarch-ap.firebasestorage.app',
    androidClientId: '804086085402-jc70la1pq4hgjfba5n8gjfuetib6vq4g.apps.googleusercontent.com',
    iosClientId: '804086085402-c5jee44v6ech7lu460atbcg80c0behm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.monarch',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQvvinCH7Enx8W__Xj2zJyGTIK7XLWPAY',
    appId: '1:804086085402:ios:6f1b37ba16975cf0585ea3',
    messagingSenderId: '804086085402',
    projectId: 'monarch-ap',
    storageBucket: 'monarch-ap.firebasestorage.app',
    androidClientId: '804086085402-jc70la1pq4hgjfba5n8gjfuetib6vq4g.apps.googleusercontent.com',
    iosClientId: '804086085402-c5jee44v6ech7lu460atbcg80c0behm0.apps.googleusercontent.com',
    iosBundleId: 'com.example.monarch',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIMDACvXox5BfCbs9sdhPijDgvLcHHYpE',
    appId: '1:804086085402:android:09608c0c11715b75585ea3',
    messagingSenderId: '804086085402',
    projectId: 'monarch-ap',
    storageBucket: 'monarch-ap.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx6IW9WmDSkbrYhVFu706X1YUdP4noQMM',
    appId: '1:804086085402:web:566a5737d0a97ebe585ea3',
    messagingSenderId: '804086085402',
    projectId: 'monarch-ap',
    authDomain: 'monarch-ap.firebaseapp.com',
    storageBucket: 'monarch-ap.firebasestorage.app',
    measurementId: 'G-2LX1YD2NGN',
  );

}